Consider redacting printing of Axis types
This PR reduces the very long stacktraces that can sometimes occur with ComponentArrays, by having by default a reducted form of `Base.show` for Axis types.

Example:
```
ERROR: MethodError: no method matching h(::ComponentMatrix{Float64, Matrix{Float64}, Tuple{Axis{...}, FlatAxis}})
Closest candidates are:
  h() at REPL[14]:1
Stacktrace:
 [1] top-level scope
   @ REPL[15]:1
```
now gives
```
ERROR: MethodError: no method matching h(::ComponentMatrix{Float64, Matrix{Float64}, Tuple{Axis{...}, FlatAxis}})
Closest candidates are:
  h() at REPL[2]:1
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```
instead of
```
ERROR: MethodError: no method matching h(::ComponentMatrix{Float64, Matrix{Float64}, Tuple{Axis{(first = 1, second = 2, third = 3, fourth = 4)}, FlatAxis}})
Closest candidates are:
  h() at REPL[2]:1
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```